### ISSUE TITLE
Terminology: Clarify "segment" or just use "line"

### ISSUE THREAD

**Issue by nbogie** [WeAreAcademy/mark-fundamentals-proj--js-xmas-tree#1]
Some scholars confused about what a segment is, thinking the foliage segment is the portion of the tree above the trunk, so they had the entire foliage being composed in makeFoliageSection. 

They preferred "foliage line" to talk about one line of foliage.

**Comment by richardcrng** [comment]
Resolved by above PR.

(In [a recent commit](https://github.com/WeAreAcademy/mark-fundamentals-proj--js-xmas-tree/commit/02a2f3b4132843b724c3604bfe26b0cc95fa489c) I've also tried to make the tests for this function clearer, so it's easier to identify the job it's meant to be doing.)
